name: Verify Python and Git Exercise

on:
  push:
    branches:
      - main  # or any default branch you're using

jobs:
  check_assignment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check Hello.py output
      run: |
        python3 hello.py > output.txt
        if ! grep -q "Hello world!" output.txt; then
          echo "Test Failed: Hello.py does not print 'Hello world!'" >> result.txt
        else
          echo "Test Passed: Hello.py prints 'Hello world!'" >> result.txt
        fi
        if ! grep -qF "$(cat intro.txt)" output.txt; then
          echo "Test Failed: Hello.py does not print the content of intro.txt" >> result.txt
        else
          echo "Test Passed: Hello.py prints the content of intro.txt" >> result.txt
        fi

    - name: Check Intro.txt content
      run: |
        intro_regex="^Name: .+\nCourse: .+\nInterests in programming: .+$"
        if ! grep -qP "$intro_regex" intro.txt; then
          echo "Test Failed: Intro.txt does not follow the correct format" >> result.txt
        else
          echo "Test Passed: Intro.txt follows the correct format" >> result.txt
        fi

    - name: Check Commit Message
      run: |
        commit_message=$(git log -1 --pretty=%B)
        if [[ "$commit_message" != "My first Python program" ]]; then
          echo "Test Failed: Commit message is not 'My first Python program'" >> result.txt
        else
          echo "Test Passed: Commit message is correct" >> result.txt
        fi

    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: submission-report
        path: report.txt
